### ISSUE TITLE
Maximum number of photos

### ISSUE THREAD

**Issue by docsnuz** [ermig1979/AntiDupl#113]
I have been trying to consolidate and clear duplicates between several online photo storage services including Amazon Photos, Google Photos and iCloud.  I have dumped all photos from all of them into one directory.  That's got over 20,000 photos.  Will running a search on this crash the application?  Or, even worse, corrupt my photos?  Is there a reasonable number of photos that I should break it up into to protect against problems?  I am running Windows 10 (latest update).  Thanks for any assistance.

**Comment by yfdyh000** [comment]
I don't think it will happen. Try it yourself, you may also have to consider time consumed and number of results.
Regarding destruction, setting the threshold to 100% will not lose any picture (also pay attention to size please), but you may care about EXIF, path, file name and other information (sounds like you are not too worried, as put them together).

**Comment by EnvarionX** [comment]
I just completed a search of an offline image library containing 43,831 items. (Mix of formats: .png .jpg .gif ...)

It took about 10 minutes to complete the scan, but speed may vary depending on your hardware since it had my CPU pinned at 100% during the scan.

Following completion of the scan the GUI remains perfectly responsive with no obvious indication of instability.
