### ISSUE TITLE
Virus Total

### ISSUE THREAD

**Issue by marcusagrippa7777** [ermig1979/AntiDupl#83]
![Screenshot (7)](https://user-images.githubusercontent.com/36614807/76685371-53196e80-65d0-11ea-9a31-b7fbaed265e1.png)

**Comment by ermig1979** [comment]
I will verify.

**Comment by ermig1979** [comment]
I checked the file by several antivirus and them didn't find any problems.

**Comment by Xav83** [comment]
Hi @ermig1979,

I am adding a message on this issue since I am facing an issue related to Virus Total.

For context, I have been mandated to maintain the Chocolatey package of [AntiDupl](https://community.chocolatey.org/packages/antidupl/2.3.10), and I am currently updating the package to make the latest version of antidupl available.
Unfortunately, I am now stuck, since that, to be validated, a chocolatey package  needs to pass the Virus Total check with less than 5 errors from security vendors, and the latest version of AntiDupl triggers [6 errors](https://www.virustotal.com/gui/file/c30774a4f22a0c5b21cf916f0d963aa2930605d4bd1ca27a2cdeac2665432623/detection).
This means that I am now stuck and can't go upload an updated version of the chocolatey package for antidupl.

![Screenshot from 2022-10-11 21-16-46](https://user-images.githubusercontent.com/6787157/195179588-d7019a6f-a3b5-426c-9e5e-478452f2ae6d.png)

I don't know, for now, what should be done to correct this issue. All I know is that there is a [GitHub Action](https://github.com/marketplace/actions/virustotal-github-action) which could help to reproduce it :wink: 

PS: You may want me to create a new issue on that topic rather than having me updating an old closed issue.
